-- ******************************************************
-- File name: direct_digital_synthesizer_top.vhd
-- Description: Top module of DDS
-- ******************************************************

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity direct_digital_synthesizer_top is
    
    generic (
    -- ******************************************************
    -- Parameters
    -- ******************************************************
        TUNING_WORD_WIDTH:       integer := 32;                                  -- Tuning word width
        WAVE_SAMPLE_VALUE_WIDTH: integer := 12;                                  -- ROM width
        TRUNCATION_SIZE:         integer := 18;                                  
        NUMBER_WAVES_TYPES:      integer := 3                                    -- The design can generate 5 wave types, so log2(5) ~ 3
    );

    port (
    -- ******************************************************
    -- Ports
    -- ******************************************************

    -- Input ports
        clk                     : in  std_logic;
        rst_n                   : in  std_logic;
        tuning_word             : in  unsigned(TUNING_WORD_WIDTH-1 downto 0);
        wave_type               : in  unsigned(NUMBER_WAVES_TYPES-1 downto 0);

    -- Output ports
        wave_sample_value       : out std_logic_vector(WAVE_SAMPLE_VALUE_WIDTH-1 downto 0)
    );

end entity direct_digital_synthesizer_top;

    -- ******************************************************
    --                     RTL
    -- ******************************************************

architecture rtl of direct_digital_synthesizer_top is

    -- ******************************************************
    -- Local Parameters
    -- ******************************************************

    constant ADDRESSING_BITS       : integer := TUNING_WORD_WIDTH-TRUNCATION_SIZE;   -- The MSBs used for LUT addr and choosing a quadrant
    constant LOG_NUMBER_OF_SAMPLES : integer := ADDRESSING_BITS - 2;                 -- ROM addr width -> Number of samples is 2^(LOG_NUMBER_OF_SAMPLES)
    constant DAC_OFFSET_VALUE      : signed(WAVE_SAMPLE_VALUE_WIDTH-1 downto 0) := to_signed(2**(WAVE_SAMPLE_VALUE_WIDTH-1), WAVE_SAMPLE_VALUE_WIDTH);

    -- ******************************************************
    -- Internal singals
    -- ******************************************************

    signal phase                    : unsigned(TUNING_WORD_WIDTH-1 downto 0); -- The phase generated by the PA unit
    signal wave_sample_value_signed : signed(WAVE_SAMPLE_VALUE_WIDTH-1 downto 0);

begin

-- **********************
-- * Phase Acucumulator *
-- **********************

 phase_accumulator_inst : entity work.phase_accumulator_top(rtl)
    generic map (
        TUNING_WORD_WIDTH => TUNING_WORD_WIDTH,
        NUMBER_WAVES_TYPES => NUMBER_WAVES_TYPES )
    port map(
        clk         => clk,
        rst_n       => rst_n,
        tuning_word => tuning_word,
        phase       => phase
);



-- **************************
-- * Wave Samples Generator *
-- **************************

 wave_samples_generator_inst : entity work.wave_samples_generator(rtl)
    generic map (
        ADDR_WIDTH             => ADDRESSING_BITS,
        DAC_WIDTH              => WAVE_SAMPLE_VALUE_WIDTH,
        NUMBER_WAVES_TYPES     => NUMBER_WAVES_TYPES,
        TRUNCATION_SIZE        => TRUNCATION_SIZE)
    port map(
        clk               => clk,
        rst_n             => rst_n,
        phase             => phase,
        wave_type         => wave_type,
        wave_sample_value => wave_sample_value_signed
);

-- **************************
-- * Offset singed  output  *
-- **************************

    wave_sample_value <= std_logic_vector(wave_sample_value_signed + DAC_OFFSET_VALUE);

end architecture rtl;
