-- ******************************************************
-- File name: phase_accumulator.vhd
-- Description: This is the phase accumulator unit.
--              It genartes the next phase of the wave
-- ******************************************************

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity phase_accumulator_top is
    
    generic (
    -- ******************************************************
    -- Parameters
    -- ******************************************************
        TUNING_WORD_WIDTH: integer := 32;
        NUMBER_WAVES_TYPES: integer := 3
    );

    port (
    -- ******************************************************
    -- Ports
    -- ******************************************************

    -- Input ports
        clk         : in  std_logic;
        rst_n       : in  std_logic;
        tuning_word : in  unsigned(TUNING_WORD_WIDTH-1 downto 0);

    -- Output ports
        phase       : out unsigned(TUNING_WORD_WIDTH-1 downto 0)
    );

end entity phase_accumulator_top;

    -- ******************************************************
    --                     RTL
    -- ******************************************************

architecture rtl of phase_accumulator_top is

    -- ******************************************************
    -- Internal singals
    -- ******************************************************

    signal phase_reg  : unsigned(TUNING_WORD_WIDTH-1 downto 0);  --(sine wave phase by default, sine the ROM holds sine wave values)
    signal phase_next : unsigned(TUNING_WORD_WIDTH-1 downto 0);

begin

-- Adder : The current phase is generated by adding
-- the tuning word to the previous phase

    phase_next <= phase_reg + tuning_word;

-- Register for sampling the phase
  
    process(clk, rst_n)
    begin
        if rst_n = '0' then
            phase_reg <= (others => '0');
        elsif rising_edge(clk) then 
            phase_reg <= phase_next;
        end if;
    end process;

 phase <= phase_reg;

end architecture rtl;
